kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.appName }}
  template:
    metadata:
      labels:
        name: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: quay.io/ecosystem-appeng/mongo-quickstart:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: {{ .Values.service.portName }}
              protocol: {{ .Values.service.protocol }}
  