apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  labels:
    name: {{ .Values.appName }}
spec:
  wildcardPolicy: None
  port:
    targetPort: {{ .Values.service.portName }}
  to:
    kind: Service
    name: {{ .Values.appName }}