apiVersion: v1
kind: Service
metadata:
  name: {{ include "create-and-connect.fullname" . }}
  labels:
    {{- include "create-and-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "create-and-connect.selectorLabels" . | nindent 4 }}
