# permissions for end users to view dbaasinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasinstance-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasinstances/status
  verbs:
  - get
